title: Your awesome title
author:
  name: GitHub User
  email: your-email@domain.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

# Build settings

# # If you clone the Minima repo and build locally, use this setting.
# theme: minima

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/). 
# If you want to use the latest Minima version on GitHub Pages, use the following setting and 
# add a line comment on "theme: minima" above.
#remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - about.md
  - contact.md

# Set to `true` to show excerpts on the homepage.
#show_excerpts: false

# If you have a favicon(tab icon) set the filepath for it below
favicon: /assets/images/icon.png

# Set links to grouping pages if you want to use them
family_page: /families
type_page: /types

# Contact Settings
contact:
  title: Send me a message
  formspree_form_id: mckaymaille@gmail.com
  form_message: You can use this to show a message above your contact form.

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  skin: dark
  social_links:
    - platform: github
      user_url: https://github.com/moaatt2
      user_title: GitHub

    - platform: email
      user_url: "mailto:mckaymaille@gmail.com"
      user_title: "mckaymaille@gmail.com" 

    - platform: code
      user_url: "https://github.com/moaatt2/minima"

    - platform: rss
      user_url: "/feed.xml"
      user_title: "RSS Feed"

# Create tippy abbreviations to use throughout the website
abbreviations:
  ar:  "<abbr title='' data-tippy-content='Aspect Ratio'>AR</abbr>"
  id:  "<abbr title='' data-tippy-content='Inner Diameter'>ID</abbr>"
  swg: "<abbr title='' data-tippy-content='Standard Wire Gauge'>SWG</abbr>"
  awg: "<abbr title='' data-tippy-content='American Wire Gauge'>AWG</abbr>"
